### PR TITLE
supoprt interface options for vxlan, such as df, local_ip and dst_port.

### PR DESCRIPTION
**Pull request by danieldin95**
```
Port "vx-100650119"
            Interface "vx-100650119"
                type: vxlan
                options: {df_default="false", dst_port="4789", key=flow, remote_ip="100.65.0.119"}
```

### CODE REVIEW

**Comment by armando-migliaccio** [comment]
Thanks for enhancing the capabilities of this library. Would it be possible to contribute a test case with your code changes? Thanks in advance!

**Comment by danieldin95** [comment]
> Thanks for enhancing the capabilities of this library. Would it be possible to contribute a test case with your code changes? Thanks in advance!

done

**Comment by franckrupin** [comment]
Hi @danieldin95  we recently moved our CI to github action and get rid of Travis, would you mind to sync your fork and merge master into your branch that would allow you to trigger the new CI.

**Comment by danieldin95** [comment]
Need I resubmit this pr?

**Comment by franckrupin** [comment]
> Need I resubmit this pr?

It's weird that the CI does not show up. Yes try to open a new PR, if  you get the CI we'll switch on the new PR.

**Pull request closed without merging**
